# Basic `dependabot.yml` file based on
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
