# Basic `dependabot.yml` file based on
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
