export enum DanRank {
  DAN_1 = "DAN_1",
  DAN_2 = "DAN_2",
  DAN_3 = "DAN_3",
  DAN_4 = "DAN_4",
  DAN_5 = "DAN_5",
  DAN_6 = "DAN_6",
  DAN_7 = "DAN_7",
  DAN_8 = "DAN_8",
  DAN_9 = "DAN_9",
  DAN_10 = "DAN_10",
  KAIDEN = "KAIDEN",
  SHINDAN_1 = "SHINDAN_1",
  SHINDAN_2 = "SHINDAN_2",
  SHINDAN_3 = "SHINDAN_3",
  SHINDAN_4 = "SHINDAN_4",
  SHINDAN_5 = "SHINDAN_5",
  SHINDAN_6 = "SHINDAN_6",
  SHINDAN_7 = "SHINDAN_7",
  SHINDAN_8 = "SHINDAN_8",
  SHINDAN_9 = "SHINDAN_9",
  SHINDAN_10 = "SHINDAN_10",
  SHINKAIDEN = "SHINKAIDEN",
}

export const DanRankDisplayName: Record<string, string> = {
  DAN_1: "1st Dan",
  DAN_2: "2nd Dan",
  DAN_3: "3rd Dan",
  DAN_4: "4th Dan",
  DAN_5: "5th Dan",
  DAN_6: "6th Dan",
  DAN_7: "7th Dan",
  DAN_8: "8th Dan",
  DAN_9: "9th Dan",
  DAN_10: "10th Dan",
  KAIDEN: "Kaiden MG",
  SHINDAN_1: "1st Shindan",
  SHINDAN_2: "2nd Shindan",
  SHINDAN_3: "3rd Shindan",
  SHINDAN_4: "4th Shindan",
  SHINDAN_5: "5th Shindan",
  SHINDAN_6: "6th Shindan",
  SHINDAN_7: "7th Shindan",
  SHINDAN_8: "8th Shindan",
  SHINDAN_9: "9th Shindan",
  SHINDAN_10: "10th Shindan",
  SHINKAIDEN: "Shinkaiden",
};
